config/routes.rb
Rails.application.routes.draw do

  get 'u38nwn0YRl8FykLLeZV9', to: 'admin_sessions#new', as: 'admin_login'
  post 'admin_sessions/create', to: 'admin_sessions#create', as: 'admin_login_process'
  get 'admin_sessions/destroy', to: 'admin_sessions#destroy', as: 'admin_logout'

  get 'home/houses', to:'home#house_list', as: 'house_list'
  get 'home/houses/:id', to:'home#house_detail', as: 'house_detail'
  
  resources :houses
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  mount_uploaders :photos, PhotoUploader
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by_email(params[:email])
    if admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to houses_url, notice: '관리자로 로그인 하였습니다.'
    else
      redirect_to admin_login_url, error: '관리자 로그인에 실패하였습니다.'
    end
  end

  def destroy
    session.delete(:admin_id) if session[:admin_id].present?
    redirect_to root_url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  protected
  def authenticate_admin_login
    unless helpers.is_admin_login?
      redirect_to admin_login_url
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def house_list
    @houses = House.all
  end

  def house_detail
    @house = House.find(params[:id])
  end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_login
  
  layout "admin_application"

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:title, :description, :address, :tel, {photos: []})
    end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper

  def is_admin_login?
    if session[:admin_id].present?
      true
    else
      false
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/admin_sessions/new.html.erb
<div class="row mt-5">
  <div class="col-md-4 offset-md-4">
    <%= form_tag("/admin_sessions/create", method: "post") do %>
      <h2 class="form-signin-heading text-center">관리자로그인</h2>
      <%= text_field_tag(:email,nil, class: 'form-control mt-3',  placeholder: '이메일') %>
      <%= password_field_tag(:password,nil, class: 'form-control mt-3',  placeholder: '비밀번호') %>

      <%= submit_tag("Login", class: 'btn btn-lg btn-primary btn-block  mt-3') %>
    <% end %>
  </div>
</div> 

app/views/home/house_detail.html.erb
<h3><%= @house.title %></h3>
<% if @house.photos.present? %>

  <div id="carouselPhotos" class="carousel slide mt-3" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @house.photos.each_with_index  do | photo, index | %>
        <li data-target="#carouselPhotos" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
      <% end %>
    </ol>
    <div class="carousel-inner" role="listbox">
      <% @house.photos.each_with_index  do | photo, index | %>
      <div class="carousel-item <%= 'active' if index == 0 %>">
        <img class="d-block img-fluid" src="<%= photo.url %>" alt="<%= @house.title %>">
      </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselPhotos" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselPhotos" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% end %>

<p class="mt-3"><%= @house.description %></p>
<p>전화번호 : <%= @house.tel %></p>
<p>주소 : <%= @house.address %></p>

app/views/home/house_list.html.erb
<% @houses.each_with_index do | house, index | %>
  <% if index % 3 == 0 %>
    <div class="card-deck mb-4">
  <% end %>
    <div class="card">
      <img class="card-img-top" src="<%= house.photos.first.thumb.url if house.photos.present? %>" alt="<%= house.title %>">
      <div class="card-block">
        <h4 class="card-title"><%= link_to house.title, house_detail_path(house) %></h4>
        <p class="card-text"><%= house.description %></p>
      </div>
    </div>   
  <% if index % 3 == 2 %>
    </div>
  <% end %>
<% end %>   

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">제주비앤비</h1>
  <p class="lead">제주의 모든 게스트하우스를 한곳에~</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/home/houses" role="button">게스트하우스 보러가기</a>
  </p>
</div>

app/views/houses/_form.html.erb
<%= form_for(house) do |f| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :tel %>
    <%= f.text_field :tel %>
  </div>
      
  <div class="field">
    <%= f.label :photos %>
    <%= f.file_field :photos, multiple: true %>
  </div>      

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Address</th>
      <th>Tel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.title %></td>
        <td><%= house.description %></td>
        <td><%= house.address %></td>
        <td><%= house.tel %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @house.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @house.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @house.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @house.tel %>
</p>

<div>
<% @house.photos.each do | photo | %>
  <img src="<%= photo.thumb.url %>" />
<% end %>
</div>   
  
<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>제주비앤비</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin_application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin_application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/houses">제주비앤비</a>

      <div class="collapse navbar-collapse" id="navbars">
        <ul class="navbar-nav justify-content-end">
          <li class="nav-item">
            <a class="nav-link" href="/admin_sessions/destroy">로그아웃</a>
          </li>
        </ul> 
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="/houses">게스트하우스 관리</a>
            </li>
          </ul>
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>제주비앤비</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-light bg-faded rounded navbar-toggleable-md">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#containerNavbar" aria-controls="containerNavbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">제주비앤비</a>

        <div class="collapse navbar-collapse" id="containerNavbar">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">서비스소개</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/home/houses">BEST 게스트하우스</a>
            </li>
          </ul>

          <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link" href="/signup">회원가입</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/login">로그인</a>
            </li>
          </ul>         
        </div>
      </nav>

    <%= yield %>

    </div> <!-- /container -->     

  </body>
</html>